export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED";

export const OPEN_DRAWER_BY_HAMBURGER = "OPEN_DRAWER_BY_HAMBURGER";
export const SHOW_HIDE_LOADER = "SHOW_HIDE_LOADER";

export const USER_LOGIN_REQ = "USER_LOGIN_REQ";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const GET_CURRENT_USER_REQ = "GET_CURRENT_USER_REQ";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR";

export const GET_ALL_DEPT_REQ = "GET_ALL_DEPT_REQ";
export const GET_ALL_DEPT_SUCCESS = "GET_ALL_DEPT_SUCCESS";
export const GET_ALL_DEPT_ERROR = "GET_ALL_DEPT_ERROR";

export const USER_LOGOUT_REQ = "USER_LOGOUT_REQ";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_ERROR = "USER_LOGOUT_ERROR";

export const PASSWORD_UPDATE_REQ = "PASSWORD_UPDATE_REQ";

export const ADD_FACULTY_REQ = "ADD_FACULTY_REQ";
export const ADD_FACULTY_SUCCESS = "ADD_FACULTY_SUCCESS";
export const ADD_FACULTY_ERROR = "ADD_FACULTY_ERROR";
