export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED";

export const OPEN_DRAWER_BY_HAMBURGER = "OPEN_DRAWER_BY_HAMBURGER";
export const SHOW_HIDE_LOADER = "SHOW_HIDE_LOADER";

export const USER_LOGIN_REQ = "USER_LOGIN_REQ";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const GET_CURRENT_USER_REQ = "GET_CURRENT_USER_REQ";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR";

export const GET_ALL_DEPT_REQ = "GET_ALL_DEPT_REQ";
export const GET_ALL_DEPT_SUCCESS = "GET_ALL_DEPT_SUCCESS";
export const GET_ALL_DEPT_ERROR = "GET_ALL_DEPT_ERROR";

export const ADD_DEPT_REQ = "ADD_DEPT_REQ";
export const ADD_DEPT_SUCCESS = "ADD_DEPT_SUCCESS";
export const ADD_DEPT_ERROR = "ADD_DEPT_ERROR";

export const UPDATE_DEPT_REQ = "UPDATE_DEPT_REQ";
export const UPDATE_DEPT_SUCCESS = "UPDATE_DEPT_SUCCESS";
export const UPDATE_DEPT_ERROR = "UPDATE_DEPT_ERROR";

export const GET_ALL_COURSE_TYPE_RQ = "GET_ALL_COURSE_TYPE_RQ";
export const GET_ALL_COURSE_TYPE_SUCCESS = "GET_ALL_COURSE_TYPE_SUCCESS";
export const GET_ALL_COURSE_TYPE_ERROR = "GET_ALL_COURSE_TYPE_ERROR";
export const GET_ALL_COURSE_REQ = "GET_ALL_COURSE_REQ";
export const GET_ALL_COURSE_SUCCESS = "GET_ALL_COURSE_SUCCESS";
export const GET_ALL_COURSE_ERROR = "GET_ALL_COURSE_ERROR";
export const GET_ALL_PRE_REQUISIT_REQ = "GET_ALL_PRE_REQUISIT_REQ";
export const GET_ALL_PRE_REQUISITE_SUCCESS = "GET_ALL_PRE_REQUISITE_SUCCESS";
export const GET_ALL_PRE_REQUISITE_ERROR = "GET_ALL_PRE_REQUISITE_ERROR";

export const GET_ALL_COLAB_AGENCY_TYPE_REQ = "GET_ALL_COLAB_AGENCY_TYPE_REQ";
export const GET_ALL_COLAB_AGENCY_TYPE_SUCCESS = "GET_ALL_COLAB_AGENCY_TYPE_SUCCESS";
export const GET_ALL_COLAB_AGENCY_TYPE_ERROR = "GET_ALL_COLAB_AGENCY_TYPE_ERROR";

export const GET_ALL_DEPT_FACILITY_REQ = "GET_ALL_DEPT_FACILITY_REQ";
export const GET_ALL_DEPT_FACILITY_SUCCESS = "GET_ALL_DEPT_FACILITY_SUCCESS";
export const GET_ALL_DEPT_FACILITY_ERROR = "GET_ALL_DEPT_FACILITY_ERROR";

export const GET_ALL_COLLABORATION_REQ = "GET_ALL_COLLABORATION_REQ";
export const GET_ALL_COLLABORATION_SUCCESS = "GET_ALL_COLLABORATION_SUCCESS";
export const GET_ALL_COLLABORATION_ERROR = "GET_ALL_COLLABORATION_ERROR";
export const ADD_COLLABORATION_REQ = "ADD_COLLABORATION_REQ";
export const ADD_COLLABORATION_SUCCESS = "ADD_COLLABORATION_SUCCESS";
export const ADD_COLLABORATION_ERROR = "ADD_COLLABORATION_ERROR";
export const UPDATE_COLLABORATION_REQ = "UPDATE_COLLABORATION_REQ";
export const UPDATE_COLLABORATION_SUCCESS = "UPDATE_COLLABORATION_SUCCESS";
export const UPDATE_COLLABORATION_ERROR = "UPDATE_COLLABORATION_ERROR";

export const ADD_COURSE_REQ = "ADD_COURSE_REQ";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_ERROR = "ADD_COURSE_ERROR";

export const UPDATE_COURSE_REQ = "UPDATE_COURSE_REQ";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_ERROR = "UPDATE_COURSE_ERROR";

export const USER_LOGOUT_REQ = "USER_LOGOUT_REQ";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_ERROR = "USER_LOGOUT_ERROR";

export const PASSWORD_UPDATE_REQ = "PASSWORD_UPDATE_REQ";

export const ADD_FACULTY_REQ = "ADD_FACULTY_REQ";
export const ADD_FACULTY_SUCCESS = "ADD_FACULTY_SUCCESS";
export const ADD_FACULTY_ERROR = "ADD_FACULTY_ERROR";

export const GET_ALL_PROGRAMME_REQ = "GET_ALL_PROGRAMME_REQ";
export const GET_ALL_PROGRAMME_SUCCESS = "GET_ALL_PROGRAMME_SUCCESS";
export const GET_ALL_PROGRAMME_ERROR = "GET_ALL_PROGRAMME_ERROR";

export const UPDATE_FACULTY_REQ = "UPDATE_FACULTY_REQ";
export const UPDATE_FACULTY_SUCCESS = "UPDATE_FACULTY_SUCCESS";
export const UPDATE_FACULTY_ERROR = "UPDATE_FACULTY_ERROR";

export const GET_ALL_FACULTY_OR_USER_REQ = "GET_ALL_FACULTY_OR_USER_REQ";
export const GET_ALL_FACULTY_OR_USER_SUCCESS = "GET_ALL_FACULTY_OR_USER_SUCCESS";
export const GET_ALL_FACULTY_OR_USER_ERROR = "GET_ALL_FACULTY_OR_USER_ERROR";
export const GET_ALL_DESIGNATIONS_REQ = "GET_ALL_DESIGNATIONS_REQ";
export const GET_ALL_DESIGNATIONS_SUCCESS = "GET_ALL_DESIGNATIONS_SUCCESS";
export const GET_ALL_DESIGNATIONS_ERROR = "GET_ALL_DESIGNATIONS_ERROR";

export const SHOW_HIDE_MODAL = "SHOW_HIDE_MODAL";
export const SELECT_ITEM_FOR_EDIT = "SELECT_ITEM_FOR_EDIT";
export const SET_SELECTED_FACULTY_USER_FOR_EDIT = "SET_SELECTED_FACULTY_USER_FOR_EDIT";

export const EDIT_MODAL_FACULTY_USER_REQ = "EDIT_MODAL_FACULTY_USER_REQ";

export const ADD_FACULTY_QF = "ADD_FACULTY_QF";
export const ADD_FACULTY_QF_SUCCESS = "ADD_FACULTY_QF_SUCCESS";
export const ADD_FACULTY_QF_ERROR = "ADD_FACULTY_QF_ERROR";

export const GET_FACULTY_QF_REQ = "GET_FACULTY_QF_REQ";
export const GET_FACULTY_QF_REQ_SUCCESS = "GET_FACULTY_QF_REQ_SUCCESS";
export const GET_FACULTY_QF_REQ_ERROR = "GET_FACULTY_QF_REQ_ERROR";

export const UPDATE_FACULTY_QF_REQ = "UPDATE_FACULTY_QF_REQ";
export const UPDATE_FACULTY_QF_SUCCESS = "UPDATE_FACULTY_QF_SUCCESS";
export const UPDATE_FACULTY_QF_ERROR = "UPDATE_FACULTY_QF_ERROR";

export const SET_SELECTED_FACULTY_QF_FOR_EDIT = "SET_SELECTED_FACULTY_QF_FOR_EDIT";